# Generated by Django 4.1.3 on 2022-11-30 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AppCoder", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estudiante",
            name="adulto",
            field=models.BooleanField(default=False),
        ),
    ]
